// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALnanJpKKV1aJRiYxxFHbWR2LxVkX2NX8',
    appId: '1:196514508240:web:40718ba6fe4374cfd09dd5',
    messagingSenderId: '196514508240',
    projectId: 'vhelp-de84f',
    authDomain: 'vhelp-de84f.firebaseapp.com',
    storageBucket: 'vhelp-de84f.appspot.com',
    measurementId: 'G-W87HPYLS59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAAo1UldTGwX0Uec9XqzVpGK1vZ2BWrV4',
    appId: '1:196514508240:android:b0778d1d837f559cd09dd5',
    messagingSenderId: '196514508240',
    projectId: 'vhelp-de84f',
    storageBucket: 'vhelp-de84f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQAR7mreI0vJryv3XF1zs_oIXd4Ct60Y',
    appId: '1:196514508240:ios:28a66a300b0cc3f5d09dd5',
    messagingSenderId: '196514508240',
    projectId: 'vhelp-de84f',
    storageBucket: 'vhelp-de84f.appspot.com',
    iosClientId: '196514508240-d0uu387n5lfa6crio48si6kb7fu69tsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.vHelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFQAR7mreI0vJryv3XF1zs_oIXd4Ct60Y',
    appId: '1:196514508240:ios:092be1da5116ae12d09dd5',
    messagingSenderId: '196514508240',
    projectId: 'vhelp-de84f',
    storageBucket: 'vhelp-de84f.appspot.com',
    iosClientId: '196514508240-e5ru14125p5i2qmvqemll7m4tpqt3cgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.vHelp.RunnerTests',
  );
}
